### ISSUE TITLE
Ability to skip precompile step?

### ISSUE THREAD

**Issue by jgadbois** [GoogleCloudPlatform/ruby-docker#147]
In our app we precompile assets ourselves (and the Google App Engine Rails tutorials say to do the same).  However, when deploying the ruby app to Google App Engine, the Dockerfile also precompiles assets, which is very slow in our build since we also compile an Ember client-side application.

Is it possible to skip the precompile step in the deploy if assets are already being served out of /public?

**Comment by dazuma** [comment]
Yes you can disable the precompile step, by setting the "build scripts" list to empty. Add this to your `app.yaml` (or merge with your existing `runtime_config` setting if you have one already)

```
runtime_config:
  build: []
```

**Comment by jgadbois** [comment]
Thanks!  Do I need to add `access_cloud_sql` to the build scripts list if I'm using cloud SQL for my database?

**Comment by dazuma** [comment]
No, not needed. `access_cloud_sql` is needed only to connect to your CloudSQL instance *for an individual build step*. For example, occasionally a Rails app needs the database connection to be live in order to boot Rails at all (e.g. even to run asset precompilation). So a build step might be `access_cloud_sql && bundle exec rake asset:precompile` to connect to CloudSQL for that build step. If you have no build steps at all, there's nothing that could need `access_cloud_sql`.

**Comment by jgadbois** [comment]
Ok, thanks so much for the help

**Comment by leomao10** [comment]
@dazuma would be great if we can specify it somewhere in the doc
