### ISSUE TITLE
env_variables in app.yaml is not available during docker build

### ISSUE THREAD

**Issue by vochicong** [GoogleCloudPlatform/ruby-docker#91]
I see that env_variables in app.yaml are available to the app running after deployment,
but they are not available during docker build.

If it is not a bug but intended, how can I pass variables to build the docker.
Concretely,  `bundle exec rake assets:precompile` fails since some variables (like DOMAIN_NAME) defined in app.yaml but not visible to the docker build process.

**Comment by dazuma** [comment]
Yes, this is a bug. We have a fix for this and a number of related issues currently in early testing, but it's not yet available publicly. For now, as a workaround, I suggest customizing the Dockerfile. See the "Extending the Runtime" section in the [docs](https://cloud.google.com/appengine/docs/flexible/ruby/runtime).

**Comment by vochicong** [comment]
Thank you. Can you give me pointers to the related issues?

Following your instruction, I've run `gcloud beta app gen-config --custom` to generate Dockerfile, then modify it to source environment secrets.

Note that I've first tried using ENV in Dockerfile, but then stopped, since it exposes the environment secrets in build log.

Sample code: https://github.com/vochicong/bootstrap4-haml-rails/blob/master/Dockerfile#L49

**Comment by dazuma** [comment]
Hi, sorry for the delay in updates.

The updated build backend for the Ruby runtime is now in beta, and we expect it to be the default in a few weeks. It fixes a variety of issues, including:

* Environment variables set in app.yaml are available to the build process (e.g. to the `bundle exec rake assets:precompile`)
* If your app uses Cloud SQL, your database is also available to the build process.

You may start using the update today by running `gcloud beta app deploy` instead of `gcloud app deploy`.

The update has a caveat, which is that all the environment variables from your app.yaml are (internally) copied into the docker image during the build process. So, as you noted in your previous comment, any "secrets" in those environment variables may appear in your Container Builder logs.

The update has a few additional features, such as customizable build commands (e.g. in addition to or instead of `bundle exec rake assets:precompile` for Rails apps), and ability to install additional debian packages without needing a custom runtime. We'll have these documented by the time the update is live, but feel free to contact me directly if you want to know how to use them.

**Comment by yuki24** [comment]
I just tried to deploy by running `gcloud beta app deploy` and it seems that it fails to start Cloud SQL Proxy:

```log
Step #1: Step 7/38 : COPY --from=gcr.io/gcp-runtimes/ruby/build-tools:2017-07-19-140548 /build_tools/ /build_tools/
Step #1: 2017-07-19-140548: Pulling from gcp-runtimes/ruby/build-tools
Step #1: 0f6202b8fe4d: Pulling fs layer
Step #1: 0f6202b8fe4d: Verifying Checksum
Step #1: 0f6202b8fe4d: Download complete
Step #1: 0f6202b8fe4d: Pull complete
Step #1: Digest: sha256:2598cdc955c6660b3ddfb80ca5efa13e0cce6418563eb0b84908ebf9b312b352
Step #1: Status: Downloaded newer image for gcr.io/gcp-runtimes/ruby/build-tools:2017-07-19-140548
Step #1:  ---> cfaf2f123024
Step #1: Removing intermediate container a1631c8414ad
Step #1: Step 8/38 : ENV PATH /build_tools:/build_tools/nodejs/bin:/build_tools/yarn/bin:${PATH}
Step #1:  ---> Running in 1a9728246a37
Step #1:  ---> 34e426d83cf0
Step #1: Removing intermediate container 1a9728246a37

...

Step #1: Step 30/38 : ARG BUILD_CLOUDSQL_INSTANCES="today-yuki-learned:us-central1:primary"
Step #1:  ---> Running in 7a2b48f15870
Step #1:  ---> 482c8205689f
Step #1: Removing intermediate container 7a2b48f15870
Step #1: Step 31/38 : RUN mkdir /cloudsql
Step #1:  ---> Running in b6673b6fbd05
Step #1:  ---> 4c27e97148ef
Step #1: Removing intermediate container b6673b6fbd05
Step #1: Step 32/38 : RUN mv google_access_token_50986622 /build_tools/access_token
Step #1:  ---> Running in 37c257f88bc3
Step #1:  ---> 7f5658b8b04e
Step #1: Removing intermediate container 37c257f88bc3
Step #1: Step 33/38 : ENV GOOGLE_ACCESS_TOKEN_FILE /build_tools/access_token
Step #1:  ---> Running in 2b3381ec534c
Step #1:  ---> 46fcb2fb11df
Step #1: Removing intermediate container 2b3381ec534c

...

Step #1: Step 35/38 : RUN /build_tools/access_cloud_sql && bundle exec rake assets:precompile || true
Step #1:  ---> Running in 8268c0ea34d5
Step #1: ERROR: Failed to start cloud_sql_proxy
Step #1:  ---> fde713e6c1e6
Step #1: Removing intermediate container 8268c0ea34d5
```

And I have the following beta settings:

```yaml
beta_settings:
  cloud_sql_instances: today-yuki-learned:us-central1:primary
```

As suggested above, I'm currently using a custom Dockerfile with `runtime: custom`. Happy to help debug this issue, let me know if there's anything I can do.

**Comment by dazuma** [comment]
@yuki24 Can you try using `runtime: ruby` instead, and not use a custom Dockerfile? Sorry I wasn't clear that the fixes do not require a custom Dockerfile. (In fact, currently custom Dockerfiles will probably have problems with cloud_sql_proxy because they cannot supply it with the right credentials, which is what you're seeing. We're working on solving this.)

**Comment by yuki24** [comment]
@dazuma Sorry I wasn't clear enough. I meant I was using `runtime: custom` with a custom Dockerfile as a workaround. What I tried was to run `gcloud beta app deploy` with `runtime: ruby` but without a custom Dockerfile, and I still see `ERROR: Failed to start cloud_sql_proxy` during the step 35/38.

**Comment by dazuma** [comment]
@yuki24 Hmm. Some things to check:

* Make sure the "Google Cloud SQL API" is enabled. (Note it is called "Google Cloud SQL API", not "Google Cloud SQL".) Visit https://pantheon.corp.google.com/apis/api/sqladmin.googleapis.com/overview to see the status.
* Make sure the cloud builder service account has permissions to see your SQL instance. Go to the IAM tab in the cloud console, and look at what roles are assigned to the service account called "<project-number>@cloudbuild.gserviceaccount.com". Try adding the "Project Editor" role if it is not already present.
* Try running cloud_sql_proxy locally and see if you can get it to connect.

**Comment by dazuma** [comment]
@yuki24 Also, we just pushed out an update to the beta runtime that cleans up some lingering auth-related issues, so it is possible your issue has also been fixed.

**Comment by yuki24** [comment]
@dazuma I just tried your suggestions, and adding the "Project Editor" role has fixed the issue. For your reference, here are the roles my `<project-number>@cloudbuild.gserviceaccount.com` currently has:

<img width="236" alt="screen shot 2017-07-31 at 21 57 49" src="https://user-images.githubusercontent.com/386234/28805963-5895848e-763b-11e7-94de-8f199f32090e.png">

Thanks so much!

**Comment by tarr11** [comment]
Trying the beta - I receive this error:

I believe this happens when you have entries that use unquoted numbers as environment variables.

FOO=1
```
Step #0: generate_dockerfile.rb:108:in `escape_quoted': undefined method `gsub' for 1:Fixnum (NoMethodError)
Step #0:        from generate_dockerfile.rb:112:in `block in render_env'
Step #0:        from generate_dockerfile.rb:112:in `each'
Step #0:        from generate_dockerfile.rb:112:in `map'
Step #0:        from generate_dockerfile.rb:112:in `render_env'
Step #0:        from (erb):106:in `write_dockerfile'
Step #0:        from /rbenv/versions/2.3.4/lib/x86_64-linux-gnu/ruby/2.3.0/erb.rb:864:in `eval'
Step #0:        from /rbenv/versions/2.3.4/lib/x86_64-linux-gnu/ruby/2.3.0/erb.rb:864:in `result'
Step #0:        from generate_dockerfile.rb:80:in `write_dockerfile'
Step #0:        from generate_dockerfile.rb:65:in `main'
Step #0:        from generate_dockerfile.rb:116:in `<main>'
```

**Comment by dazuma** [comment]
@tarr11 Thanks for the report. That has now been fixed in the latest release.

Also, the updated build pipeline is now live for all deploys as of the latest release of the gcloud SDK (version 169.0.0). That should fix this issue, so I'm closing it now.

**Comment by vochicong** [comment]
Thank you for the fix @dazuma !

**Comment by slorg1** [comment]
Hi, I am check-in on this @dazuma 

I seem to be having the exact same issue:
* using Ruby 3.1
* Rails 7
* Appegine with the Ruby runtime
```
env: flex
runtime: ruby
```

When building I get this:
```
Step #2: Step 14/17 : RUN access_cloud_sql --lenient && bundle exec rake assets:precompile || true
Step #2:  ---> Running in 8e4e10201bec
Step #2: Started cloud_sql_proxy.
Step #2: rake aborted!
Step #2: ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
```
my `env_variables` and `build_env_variables` both set the secret key base and the environment is set to `staging` (clearly ignored).

Was the issue fixed in 2017 and back in 2024? Or is there something I am doing wrong to pass environment variables to the build process (when running `gcloud app deploy` it triggers a *Cloud Build*.

As you can see while I was initially getting the error with cloud SQL it seems like I was able to figure it out
